### ISSUE TITLE
♻️ [Refactor] Repository 패턴 적용

### ISSUE THREAD

**Issue by kanghyki** [42connected/polar#425]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

### 📦 Repository와 ⚙️ 서비스 분리

<img width="677" alt="code" src="https://user-images.githubusercontent.com/94736461/202199040-10870179-cbc4-4d6b-a9e8-bfd4ea4d2542.png">

위 사진과 같이 DB와 서비스가 강하게 결합되어 있는 상태입니다.

그래서 Repository패턴을 적용하여 프로젝트를 리팩토링 하고자 합니다.

## 📝 리팩토링 상세 내용

`findByIntraId`와 같은 메소드들을 @.repository.ts 파일로 분리하여 인터페이스를 적용해 값을 리턴하고,

서비스는 `오로지 서비스 로직에만 집중`할 수 있게 만들고자 합니다.

## ✅ TODO

- [ ] 중복 코드 제거

- [ ] 인터페이스 정의

- [ ] 함수 재정의

## 📍 레퍼런스
[Design the infrastructure persistence layer](https://learn.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-design)
[[ NestJS ] Repository Pattern에 대하여 알아보자](https://tasddc.tistory.com/124)
