### ISSUE TITLE
🚨 [Bug] 멘토 - 나의 멘토링 : 멘토링 상태 '취소'가 가장 위로 올라옴

### ISSUE THREAD

**Issue by Joo-hyun-Kang** [42connected/polar#426]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 🐛 버그 개요

1. 멘토 나의 멘토링 : 멘토링 상태 '취소'가 가장 위로 올라옴
2. 멘토 나의 멘토링 : 정렬상태가 신청일시 순서가 아님

## 🐞 버그 상세 내용
1. 멘토 나의 멘토링 : 멘토링 상태 '취소'가 가장 위로 올라옴
[멘토님이 작성한 버그 리포트 ]
취소 멘토링 보이지 않게 설정
나의 멘토링에서 취소한 멘토링이 항상 상단에 떠있는게 불편해요. 취소한 멘토링은 취소 되었다는 사실 한번만 알면 될 것 같은데 계속 표에 (그것도 상단에) 나와있어서 자꾸 실수로 누르게 돼요.

개선안 (의견입니다)
멘토링 신청과 멘토링 이력이 분리가 되면 좋겠습니다. 현재는 멘토링 신청과 이력이 하나의 표에 있기 때문에 어떤 걸 확정해야 하는지 / 어떤 걸 보고서 작성해야 하는지 분간이 어려워요. 차라리 표를 두 개로 나눠서 신청 표와 멘토링 이력 표 두 가지를 나눠보는 건 어떨까요? 그리고 신청 취소를 하면 그 신청 사실은 다시 안 봐도 될 것 같아요.
-> 정리하면 표에 있는 상태column과 보고서column에 따라 표를 나눴으면 합니다

2. 멘토 나의 멘토링 : 정렬상태가 신청일시 순서가 아님
나의 멘토링 페이지 가면 신청일시 기준으로 정렬 되어야 한다고 생각하는데, 보니까 상태 기준으로 정렬이 되는 것 같습니다! 한 번 확인해주시면 좋을 것 같아요~~

[jokang의 제안]
멘토님이 말한 개선사항은 프론트 작업이 필요함으로 프론트에서 천천히 처리
취소가 위로 올라오는 건 긴급하게 해결하면 좋을 듯합니다

## ✅ TODO

- [ ] 백엔드에서 API 수정하여 멘토링 상태 취소를 가장 아래 row에 보이게 수정
- [ ] 나의 멘토링 - 멘토에 정렬 알고리듬이 신청일자 순서로 오는 지 점검하기

## 📍 레퍼런스
https://polar-bne7366.slack.com/archives/C0492BL7P2M/p1668039453313119
https://polar-bne7366.slack.com/archives/C0492BL7P2M/p1667900221551639

**Comment by kanghyki** [comment]
@Joo-hyun-Kang 
## ✏️ 멘토 나의 멘토링 : 멘토링 상태 '취소'가 가장 위로 올라옴

<img width="1203" alt="Screenshot 2022-11-18 at 6 39 43 PM" src="https://user-images.githubusercontent.com/94736461/202670758-c428fdf4-4a34-4f73-827f-405a4082cbd3.png">

취소 상태인 멘토링 로그가 가장 위로(최상단) 올라오는 현상을 발견하지 못했습니다.

사진이나 상황을 첨부해주시면 감사하겠습니다. 🙇‍♂️

## ✏️ 멘토 나의 멘토링 : 정렬 상태가 신청일시 순서가 아님

현재 `신청 일시`가 아닌 `meetingStart`을 기준으로 정렬되고 있습니다

프로젝트 기획 단계에서 신청 일시로 정렬할 경우 먼 미래에 잡아놓은 멘토링이 보이지 않을 수 있다는 우려 때문에

`meetingStart`을 기준으로 정렬하게 되었는데 논의가 필요할 것 같습니다.

**Comment by Joo-hyun-Kang** [comment]
@kanghyki 
✏️ 멘토 나의 멘토링 : 멘토링 상태 '취소'가 가장 위로 올라옴
<img width="1092" alt="Screen Shot 2022-11-18 at 8 27 04 PM" src="https://user-images.githubusercontent.com/68218329/202695085-fc2f6082-7a44-4b22-8a2f-982db41566c6.png">

테스트 디비가 2개 있는데 다른 디비를 연결해보시면 위와 같은 결과를 얻을 수 있습니다
취소라서 위로 올라가는게 아니라 멘토링 시간이 없는 경우 위로 올라가는 것 같습니다

**Comment by kanghyki** [comment]
@Joo-hyun-Kang 

아하 meetingStart가 없는 로그가 최상단으로 올라가네요

신청 일시 기준으로 정렬하도록 하면

```
멘토 나의 멘토링 : 멘토링 상태 '취소'가 가장 위로 올라옴
멘토 나의 멘토링 : 정렬상태가 신청일시 순서가 아님
```
위에 두 문제 다 해결할 수 있을 것 같은데

어떻게 생각하시나요?

**Comment by Joo-hyun-Kang** [comment]
@kanghyki 
일단 멘토링 상태시간으로 하고 취소만 뒤로 옮기면 좋을 것 같아요
프론트 리펙토링할 때 신청시간과 멘토링 시간을 선택해서 정렬 할 수 있게 수정하려고 합니다
